config/routes.rb
Rails.application.routes.draw do

resources :cities do 
	collection do
		get 'search'
		get :autocomplete
	end
end

#user routes
get '/signup', to: 'users#new'
get '/profile', to: 'users#show'
resources :users, only: [:create, :edit, :update]

#session routes
get "/login", to: "sessions#new"
get "/logout", to: "sessions#destroy"
post "/sessions", to: "sessions#create"

# posts routes
resources :posts

root 'home#index'

end

#              Prefix Verb   URI Pattern                    Controller#Action
#         cities_show GET    /cities/show(.:format)         cites#show
#        cities_index GET    /cities/index(.:format)        cities#index
#                city GET    /cities/:id(.:format)          cities#show
#       search_cities GET    /cities/search(.:format)       cities#search
# autocomplete_cities GET    /cities/autocomplete(.:format) cities#autocomplete
#              cities GET    /cities(.:format)              cities#index
#                     POST   /cities(.:format)              cities#create
#            new_city GET    /cities/new(.:format)          cities#new
#           edit_city GET    /cities/:id/edit(.:format)     cities#edit
#                     GET    /cities/:id(.:format)          cities#show
#                     PATCH  /cities/:id(.:format)          cities#update
#                     PUT    /cities/:id(.:format)          cities#update
#                     DELETE /cities/:id(.:format)          cities#destroy
#              signup GET    /signup(.:format)              users#new
#             profile GET    /profile(.:format)             users#show
#               users POST   /users(.:format)               users#create
#               login GET    /login(.:format)               sessions#new
#              logout GET    /logout(.:format)              sessions#destroy
#            sessions POST   /sessions(.:format)            sessions#create
#               posts GET    /posts(.:format)               posts#index
#                     POST   /posts(.:format)               posts#create
#            new_post GET    /posts/new(.:format)           posts#new
#           edit_post GET    /posts/:id/edit(.:format)      posts#edit
#                post GET    /posts/:id(.:format)           posts#show
#                     PATCH  /posts/:id(.:format)           posts#update
#                     PUT    /posts/:id(.:format)           posts#update
#                     DELETE /posts/:id(.:format)           posts#destroy
#                root GET    /                              home#index

app/models/city.rb
class City < ActiveRecord::Base
has_many :posts


	 # searchkick autocomplete: ['name']

	# def autocomplete
 #    render json: City.search(params[:search], autocomplete: true, limit: 10).map(&:name)
 #  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :cities
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_secure_password 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #form to create new user
  def new
    if current_user
      redirect_to profile_path
    else
      @user = User.new
      render :new
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    unless current_user
      redirect_to login_path
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	def search
		if params[:search].present?
			cities = City.where("name LIKE ?", params[:search])
			if cities.any?
				@city = cities.first
				redirect_to city_path(@city)
			else
				redirect_to cities_path
			end
		else
			redirect_to cities_path
		end
	end	


  def index
  	@cities = City.all
  	render :index
  end

	  def show
	  	city_id = params[:id]
	  	@city = City.find_by(id: city_id)
	  	@post = Post.where(city_id: city_id)
	  	render :show
	  end

	  def post_params
	    params.require(:post).permit(:author, :title, :body)
	  end
	end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@city = City.first(6)
  	render :index
  end
  def show
  	@city = City.all
  	render :show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
 #authorizes pages except index and show pages
 before_filter :authorize, except: [:index, :show] 
  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    post = current_user.posts.create(post_params)
    #redirect to '/users/post'
    redirect_to post_path(post)
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    if current_user.posts.include? @post
      render :edit
    else
      # redirect_to '/profile'
      redirect_to profile_path
    end
  end

  def update
    post = Post.find(params[:id])
    if current_user.posts.include? post
      post.update_attributes(post_params)
      redirect_to post_path(post)
    else
      redirect_to profile_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :city_id, :author, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  	if @current_user
  		redirect_to profile_path
  	else
	  	render :new
  	end
  end

  def create
  	user = User.find_by_email(user_params[:email])
  	if user && user.authenticate(user_params[:password])
  		session[:user_id] = user.id
  		redirect_to profile_path
  	else
  		redirect_to login_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # form to create new user
  def new
    if current_user
      redirect_to profile_path
    else
      @user = User.new
      render :new
    end
  end

  # creates new user in db
  def create
    if current_user
      redirect_to profile_path
    else
    user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to '/profile'
      else
        redirect_to '/signup'
      end 
    end
  end

  # show current user 
  def show
  	@current_user = User.find(session[:user_id])
    @posts = @current_user.posts
    @post = Post.new
    @cities = City.all
  	render :show
  end

  # form to edit user details
  def edit
    @user = User.find(params[:id])
  end

  def update
    @current_user = User.find(session[:user_id])
    @user =  @current_user
    if current_user.users.include? user
      user.update_attributes(user_params)
    end
  end

  
  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
	<div id="background" class="container-fluid">
		<div class="col-sm-6 text-center col-sm-offset-3">
			<% @cities.each do |city| %>
				<div class="city_wrapper">
					<h2 class="name"><%= city.name %></h2>
					<img src="<%= city.image %>" alt="">
				</div>

			<% end %>
		</div>
	</div>
</body>

<head>
</head>

<script src='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.css' rel='stylesheet' />

<body>
<div class="jumbotron">
  <div class="container">
    <h1> Where shall we go?</h1>
    <p> chose a city to explore. </p>

  </div>
</div>

    <!-- <h4>/h4> -->
    <iframe width='100%' height='500px' frameBorder='0' src='https://a.tiles.mapbox.com/v4/julfi.fd2c80c9/attribution,zoompan,zoomwheel,geocoder,share.html?access_token=pk.eyJ1IjoianVsZmkiLCJhIjoiNzVjZTUxZmJmMTMwNTIwMTUwYWUzYWMwZmY2NjVhMzcifQ.iYluRvwwQChus9Ublk3lcg'></iframe>
  </div>


  <div id='map'></div>
</div>

</body>
    </script>

app/views/cities/search.html.erb
<% @cities.each do |city| %>
	<div class="post_wrapper">
		<h2 class="name"><%= link_to city.name, city %></h2>
	</div>
<% end %>

app/views/cities/show.html.erb
<div class="city">
	<img id="bg-img" src="<%= @city.bg_img %>" alt="<%= @city.name %> Background Image">
	<div id="main" class="container-fluid">
		<div class="col-sm-10 col-sm-offset-1 main">
			<div class="row">
				<h4 class="name col-sm-6"><%= link_to @city.name %></h4>
				<% if current_user.present? %>
				<button role="button" class="col-sm-6 text-right btn btn-primary btn-lg red-btn" data-toggle="modal" data-target="#newPostModal">Create New Post</button>
				<% end %>
			</div>			
			<img class="banner-image col-sm-12" src="<%= @city.banner_image %>">
			<div class="cities-posts col-sm-12">
				<% @post.each do |post| %>
					<h1><%= post.title %></h1>
					<h4><%= post.author %></h4>
					<p><%= post.body %></p>
				<% end %>
				<%= render 'posts/new' %>
			</div>
			</div>
		</div>
	</di>

</div>

app/views/home/index.html.erb
<div class="home">
	<div id="background" class="container-fluid">
		<div class="col-sm-6 text-center col-sm-offset-3">
			<p class="animated fadeInDown" id="go-somewhere">Go.</p>
		    <%= form_tag search_cities_path, method: :get, class: "input-group animated fadeIn fade", id: "city_search", autocomplete: "on", role: "search" do %>
		    		<%= text_field_tag :search, params[:search], placeholder: "Where Are You Headed?", class:"form-control" %>
		    		<span class="input-group-btn">
		    		<%= submit_tag "Go!", name: nil, class: "btn btn-default" %>
					</span>
		    <% end %>
		  </div>

		  <div class="col-sm-8 text-center col-sm-offset-2">
			  <div class="row animated fadeIn fade">
			  	<% @city.each do |city| %>
			  		<div class="col-sm-4">
			  			<h4 class="name"><%= link_to city.name, city_path(city) %></h4>
			  			<img src="<%= city.image %>">
			  		</div>
			  	<% end %>
			  </div>
		  </div>
	</div>
</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='http://fonts.googleapis.com/css?family=Kalam:700|Quicksand:400,700,300|Montserrat:700' rel='stylesheet' type='text/css'>
  <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
 	<% if current_user.present? %>
		<nav id="nav" class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand logo" href="/">Vagabond</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">

		      	<li><a href="/cities">Browse Cities</a></li>
		      	<li><a href="/profile">Profile</a></li>
		        <li><a href="/logout">Log Out</a></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	<% else %>
		<nav id="nav" class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand logo" href="/">Vagabond</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		      	<li><a href="/cities">Browse Cities</a></li>
		      	<!-- Button trigger sign up modal -->
		      	<li><button role="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signupModal">
		      	  Sign Up
		      	</button></li>
		      	<!-- Button trigger login modal -->
		      	<li><button role="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#loginModal">
		      	  Login
		      	</button></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

	<% end %>

	<%= render 'users/login' %>
	<%= render 'users/new' %>
<div id="main_content">
<%= yield %>
</div>
	<%= javascript_include_tag :application %>
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script> -->
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 
</body>
</html>

app/views/posts/_edit.html.erb
<div class="modal fade" id="editPostModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Post</h4>
      </div>
      <div class="modal-body">
          <%= form_for @post, url: posts_path do |f| %>
              <%= f.text_field :title, placeholder: "title", class: "form-control" %>
              <%= f.collection_select(:city_id, City.all, :id, :name ) %>
              <%= f.text_field :author, placeholder: "author", class: "form-control" %><br>
              <%= f.text_area :body, placeholder: "body", class: "form-control" %>
              <%= f.submit "Post", class: "red-btn"%>
          <% end %>
      </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/posts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h1 >New Post</h1>
			<%= form_for @post do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><%= f.text_field :title, placeholder: "title" %></h3>
			    <%= f.collection_select(:city_id, City.all, :id, :name ) %>
			  </div>
			  <div class="panel-body">
			  	<%= f.text_field :author, placeholder: "author" %><br>
			    <%= f.text_field :body, placeholder: "body" %>
			  </div>
			</div>
  		<hr>
  		<%= f.submit "Save Post" %>
		</div>
	</div>
</div>

app/views/posts/_new.html.erb
<div class="modal fade" id="newPostModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Post</h4>
      </div>
      <div class="modal-body">
          <%= form_for Post.new, url: posts_path do |f| %>
              <%= f.text_field :title, placeholder: "title", class: "form-control" %>
              <%= f.collection_select(:city_id, City.all, :id, :name ) %>
              <%= f.text_field :author, placeholder: "author", class: "form-control" %><br>
              <%= f.text_area :body, placeholder: "body", class: "form-control" %>
              <%= f.submit "Post", class: "red-btn"%>
          <% end %>
      </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/posts/_newPost.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h1 >New Post</h1>
			<%= form_for @post do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><%= f.text_field :title, placeholder: "title" %></h3>
			    <%= f.collection_select(:city_id, City.all, :id, :name ) %>
			  </div>
			  <div class="panel-body">
			  	<%= f.text_field :author, placeholder: "author" %><br>
			    <%= f.text_field :body, placeholder: "body" %>
			  </div>
			</div>
  		<hr>
  		<%= f.submit "Save Post" %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<body class="posts">
<div id="background2" class="container-fluid">
	<div class="col-sm-8 text-center col-sm-offset-2">
		<div class="row animated fadeIn fade">
			<h4 id="city-name1"></h4><br>
			<img id="profile-image2" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/08b/0a4/1e476e9.jpg" alt="Daniel Kahn">
						<div id="post_content">
							<h2 class="title" id="titleId"><%= link_to post.title, post %></h2>
							<h4 class="author"><%= post.author %></h4>
							<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
							<h4 class="body"><%= post.body %></h4>
						</div>
			</div>
		</div>
	</div>
</body>
<% end %>

app/views/posts/new.html.erb
<!-- <div class="container">
	<div class="row">
		<div class="col-md-8">
			<h1 >New Post</h1>
			<%= form_for @post do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><%= f.text_field :title, placeholder: "title" %></h3>
			    <%= f.collection_select(:city_id, City.all, :id, :name ) %>
			  </div>
			  <div class="panel-body">
			  	<%= f.text_field :author, placeholder: "author" %><br>
			    <%= f.text_field :body, placeholder: "body" %>
			  </div>
			</div>


<%= render 'form' %>
</div>


  		<hr>
  		<%= f.submit "Save Post" %>
		</div>
	</div>
</div>
<% end %> -->

app/views/posts/show.html.erb
<!-- <body class="posts">
<div id="background2" class="container-fluid">
	<div class="col-sm-8 text-center col-sm-offset-2">
		<div class="animated fadeIn fade">
			<h4 id="city-name1"></h4><br>
			<img id="profile-image2" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/08b/0a4/1e476e9.jpg" alt="Daniel Kahn">
			<div id="post_content">
				<h2 class="title" id="titleId">Sunny California</h2>
				<h3 class="author">Michelle M.</h3>
				<p class="date">
					Submitted about 20 hours Ago
				</p>
				<p class="body">
					California, a western U.S. state, stretches from the Mexican border along the Pacific for nearly 900 miles. It&#39;s known for its dramatic terrain encompassing cliff-lined beaches, redwood forest, the Sierra Nevada Mountains, Central Valley farmland and the arid Mojave Desert. Its cities include sprawling Los Angeles, seat of the Hollywood entertainment industry, and hilly San Francisco, home to the Golden Gate Bridge.
				</p>
			</div>
		</div>
	</div>
	
</div> -->
<%= render 'posts/edit' %>
<div class="post">
	<img id="bg-img" src="<%= City.find(@post.city_id).banner_image %>" alt="Background Image">
	<div class="post-bg">
		<div class="container-fluid">
			<div id="content-div" class="row col-sm-8 col-sm-offset-2">
				<div class="row col-sm-offset-9">
					<!-- Button trigger modal -->
					<button id="edit-post-btn" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#editPostModal">
					  Edit Post
					</button>
					
					<%= link_to "", @post, method: :delete, class: "glyphicon glyphicon-trash edit-post" %>
				</div>
				<div class="col-sm-3">
				<img id="profile-image2" src="<%= City.find(@post.city_id).image %>">
				</div>
				<div class="col-sm-9">
					<h1><%= @post.title %></h1>
					<h3><%= @post.author %></h3>
					<h4><%= City.find(@post.city_id).name %></h4>
					<p><%= @post.body %></p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_createPost.html.erb
_createPost.html.erb

app/views/users/_editProfile.html.erb
<!-- modal for Edit Profile -->
<div class="modal fade" id="editProfileModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Edit Profile</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<%= form_for :user, url: users_path do |f| %>
					    <%= f.text_field :first_name, value: @current_user[:first_name] %> <br>
					    <%= f.text_field :last_name, value: @current_user[:last_name] %><br>
					    <%= f.email_field :email, value: @current_user[:email] %><br>
					    <%= f.collection_select(:city_id, City.all, :id, :name ) %><br>
					    <%= f.submit "Update Profile" %>
					<% end %>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_login.html.erb
<!-- modal for sign up -->
<div class="modal fade" id="loginModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Log In</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<%= form_for :user, url: sessions_path do |f| %>
					  <%= f.email_field :email, placeholder: "Email", class: "form-control"  %><br>
					  <%= f.password_field :password, placeholder: "Password", class: "form-control"  %><br>
					  <hr>
					  <%= f.submit "Log In" %>
					<% end %>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_new.html.erb
<!-- modal for sign up -->
<div class="modal fade" id="signupModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Sign Up!</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<%= form_for :user, url: '/users' do |f| %>
					    <%= f.text_field :first_name, placeholder: "First Name" %><br>
					    <%= f.text_field :last_name, placeholder: "Last Name" %><br>
					    <p id="current-city">Choose Your Current City:</p><%= f.collection_select(:city_id, City.all, :id, :name )%><br>
					    <%= f.email_field :email, placeholder: "Email" %><br>
					    <%= f.password_field :password, placeholder: "Password" %><br>
					    <%= f.submit "Sign Up", id: "signup-btn" %>
					<% end %>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    <%= f.email_field :email, placeholder: "Email" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<%= render 'posts/new' %>
<%= render 'users/editProfile' %>
<div class="container-fluid">
	<button id="profile-post" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newPostModal">Create New Post</button>
<div class="profile-background">
	<div id="profile">
		<div id="profile2">
			<img id="profile-image" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/08b/0a4/1e476e9.jpg" alt="Michelle">
		</div>
		<div>
			<p class="profile-text"><%= @current_user.first_name.capitalize %> <%= @current_user.last_name.capitalize %></p>
		<p class="profile-text"><%= @current_user.created_at.strftime("%B, %d, %Y") %></p>
		<p id="city"><%= @current_user.current_city %></p>
		<button id="edit-profile" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#editProfileModal">Edit Profile</button>
				
		</div>
	</div>
</div>
</div>


<div class="container-fluid">
<div class="row col-sm-12 text-center">
	<h1 id="posts-area-title">Your Posts</h1>
</div>
<% @posts.each do |post| %>
	<div class="col-sm-8 col-sm-offset-2">
		<div class="city-image col-sm-2">
			<% @cities.each do |city| %>
		      <% if city.id == post.city_id %>
				<img src = <%= city.image %>>
		      <% end %>
			<% end %>
		</div>
		<div class="col-sm-8 post-list">
			<h2><a href="/posts/<%= post.id %>"><%= post.title %></a></h2>
			<p><%= post.body %></p>
			<hr>
		</div>
	</div>
<% end %>